name: Build, Test, and Lint

on:
  push:
    branches:
      - prisma
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
        volumes:
          - db-data:./mysql/var/lib/mysql
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NODE_ENV: "test"
      NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
      NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
      SHADOW_DATABASE_URL: ${{secrets.SHADOW_DATABASE_URL}}
      DISCORD_CLIENT_ID: ${{secrets.DISCORD_CLIENT_ID}}
      DISCORD_CLIENT_SECRET: ${{secrets.DISCORD_CLIENT_SECRET}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
