name: Build, Test, and Lint

on:
  push:
    branches:
      - prisma
      - main

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  NODE_ENV: "test"
  NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
  NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
  SHADOW_DATABASE_URL: ${{secrets.SHADOW_DATABASE_URL}}
  DISCORD_CLIENT_ID: ${{secrets.DISCORD_CLIENT_ID}}
  DISCORD_CLIENT_SECRET: ${{secrets.DISCORD_CLIENT_SECRET}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Docker Compose Action
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Test
        run: npm run test

      - name: Docker Compose Down
        run: docker-compose down

      - name: Lint
        run: npm run lint
