name: Build, Test, and Lint

on:
  push:
    branches:
      - prisma
      - main

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  NODE_ENV: "test"
  NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
  NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
  SHADOW_DATABASE_URL: ${{secrets.SHADOW_DATABASE_URL}}
  DISCORD_CLIENT_ID: ${{secrets.DISCORD_CLIENT_ID}}
  DISCORD_CLIENT_SECRET: ${{secrets.DISCORD_CLIENT_SECRET}}

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        restart: always
        container_name: intergration-tests-prisma
        ports:
          - 3306:3306
        environment:
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        expose:
          - 3306
        volumes:
          - ./mysql:/var/lib/mysql
    volumes:
      tests:

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test:ci

      - name: Docker Compose Down
        run: docker-compose down

      - name: Lint
        run: npm run lint
